# permissions for end users to view healths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: health-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: propagation-controller
    app.kubernetes.io/part-of: propagation-controller
    app.kubernetes.io/managed-by: kustomize
  name: health-viewer-role
rules:
- apiGroups:
  - kuberik.io
  resources:
  - healths
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuberik.io
  resources:
  - healths/status
  verbs:
  - get
