# This rule is not used by the project propagation-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over promotion.kuberik.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: propagation-controller
    app.kubernetes.io/managed-by: kustomize
  name: promotion-releasepromotion-admin-role
rules:
- apiGroups:
  - promotion.kuberik.io
  resources:
  - releasepromotions
  verbs:
  - '*'
- apiGroups:
  - promotion.kuberik.io
  resources:
  - releasepromotions/status
  verbs:
  - get
