# This rule is not used by the project propagation-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the promotion.kuberik.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: propagation-controller
    app.kubernetes.io/managed-by: kustomize
  name: promotion-releasepromotion-editor-role
rules:
- apiGroups:
  - promotion.kuberik.io
  resources:
  - releasepromotions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - promotion.kuberik.io
  resources:
  - releasepromotions/status
  verbs:
  - get
