# permissions for end users to edit propagations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: propagation-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: propagation-controller
    app.kubernetes.io/part-of: propagation-controller
    app.kubernetes.io/managed-by: kustomize
  name: propagation-editor-role
rules:
- apiGroups:
  - kuberik.io
  resources:
  - propagations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuberik.io
  resources:
  - propagations/status
  verbs:
  - get
