---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kuberik.io
  resources:
  - propagations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuberik.io
  resources:
  - propagations/finalizers
  verbs:
  - update
- apiGroups:
  - kuberik.io
  resources:
  - propagations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - promotion.kuberik.io
  resources:
  - releasepromotions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - promotion.kuberik.io
  resources:
  - releasepromotions/finalizers
  verbs:
  - update
- apiGroups:
  - promotion.kuberik.io
  resources:
  - releasepromotions/status
  verbs:
  - get
  - patch
  - update
