apiVersion: kuberik.io/v1alpha1
kind: Propagation
metadata:
  labels:
    app.kubernetes.io/name: propagation
    app.kubernetes.io/instance: propagation-sample
    app.kubernetes.io/part-of: propagation-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: propagation-controller
  name: propagation-sample
spec:
  # TODO(user): Add fields here
