apiVersion: kuberik.io/v1alpha1
kind: Propagation
metadata:
  name: my-app
spec:
  backend: s3://my-deployments-8fiuv6/k8s/
  deployment:
    group: prod-my-team
    name: zurich-1
    version:
      kind: Kustomization
      fieldPath: status.lastAppliedRevision
    healthStatus:
      interval: 24h
      labelSelector:
        kuberik.io/propagation: my-app
  deployAfter:
    deployments:
      - zurich-1-staging
    group: staging
    interval: 4h
